#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCApp;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Person/Partial/_AddNewBadge.cshtml")]
    public partial class _Views_Person_Partial__AddNewBadge_cshtml : System.Web.Mvc.WebViewPage<MVCApp.ViewModels.SelectBadgesViewModel>
    {
        public _Views_Person_Partial__AddNewBadge_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h3>Add New Badge</h3>\r\n<form");

WriteLiteral(" id=\"add_badge_form\"");

WriteLiteral(" class=\"form-horizontal col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 5 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.LabelFor(m => m.PersonName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.TextBoxFor(m => m.PersonName, new {@class = "form-control", id = "person_name", person_id = @Model.PersonId, @readonly = "true"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.ValidationMessageFor(m => m.PersonName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.LabelFor(m => m.Badges));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
          
            var badgesToSelect = Model.Badges.Select(i => new SelectListItem()
            {
                Text = i.Title,
                Value = i.Id + ""
            });
        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.DropDownListFor(m => m.Badges, badgesToSelect, new {@class = "form-control", id = "badge_dropdown"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
   Write(Html.ValidationMessageFor(m => m.Badges));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" Value=\"Add Badge\"");

WriteLiteral("/>\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Views\Person\Partial\_AddNewBadge.cshtml"
Write(Html.ActionLink("Cancel", "Index", "Person", null, new {@class = "btn-danger btn"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n</form>");

        }
    }
}
#pragma warning restore 1591
