#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCApp;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Person/Partial/_PersonTable.cshtml")]
    public partial class _Views_Person_Partial__PersonTable_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<MVCApp.ViewModels.PersonViewModel>>
    {
        public _Views_Person_Partial__PersonTable_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral(" id=\"person_table\"");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n    <tr");

WriteLiteral(" class=\"table-header\"");

WriteLiteral(">\r\n        <th>Photo</th>\r\n        <th>Name</th>\r\n        <th>Birthdate</th>\r\n   " +
"     <th>Age</th>\r\n        <th>Badges</th>\r\n        <th>New Badge</th>\r\n        " +
"<th>Edit</th>\r\n        <th>Delete</th>\r\n    </tr>\r\n");

            
            #line 13 "..\..\Views\Person\Partial\_PersonTable.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Person\Partial\_PersonTable.cshtml"
     foreach (var person in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr");

WriteAttribute("id", Tuple.Create(" id=\"", 404), Tuple.Create("\"", 419)
            
            #line 15 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 409), Tuple.Create<System.Object, System.Int32>(person.Id
            
            #line default
            #line hidden
, 409), false)
);

WriteLiteral(">\r\n            <td>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 461), Tuple.Create("\"", 558)
            
            #line 17 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 467), Tuple.Create<System.Object, System.Int32>(Url.Action("GetPhoto", "Person", new {personId = @person.Id, fileName = @person.PhotoUrl})
            
            #line default
            #line hidden
, 467), false)
);

WriteLiteral(" class=\"photoImg\"");

WriteLiteral(" />\r\n            </td>\r\n            <td");

WriteLiteral(" name=\"name\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Person\Partial\_PersonTable.cshtml"
                       Write(person.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td");

WriteLiteral(" name=\"birthDate\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Person\Partial\_PersonTable.cshtml"
                            Write(person.BirthDate.ToString("MM/dd/yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 21 "..\..\Views\Person\Partial\_PersonTable.cshtml"
           Write(person.Age);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>\r\n                <div");

WriteLiteral(" class=\"add_badge_container\"");

WriteLiteral(">\r\n");

            
            #line 24 "..\..\Views\Person\Partial\_PersonTable.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Person\Partial\_PersonTable.cshtml"
                     foreach (var badge in person.Badges)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"badge_item\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("img_id", Tuple.Create(" img_id=\"", 994), Tuple.Create("\"", 1012)
            
            #line 27 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1003), Tuple.Create<System.Object, System.Int32>(badge.Id
            
            #line default
            #line hidden
, 1003), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 1013), Tuple.Create("\"", 1106)
            
            #line 27 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1019), Tuple.Create<System.Object, System.Int32>(Url.Action("GetImage", "Badge", new {badgeId = @badge.Id, fileName = @badge.ImageUrl})
            
            #line default
            #line hidden
, 1019), false)
);

WriteAttribute("title", Tuple.Create(" \r\n                                 title=\"", 1107), Tuple.Create("\"", 1162)
            
            #line 28 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1150), Tuple.Create<System.Object, System.Int32>(badge.Title
            
            #line default
            #line hidden
, 1150), false)
);

WriteLiteral(" class=\"photoImg img-circle\"");

WriteLiteral(" />\r\n                        </div>\r\n");

            
            #line 30 "..\..\Views\Person\Partial\_PersonTable.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </td>\r\n            <td><button");

WriteLiteral(" name=\"add_new_badge\"");

WriteAttribute("person_id", Tuple.Create(" person_id=\"", 1338), Tuple.Create("\"", 1360)
            
            #line 33 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1350), Tuple.Create<System.Object, System.Int32>(person.Id
            
            #line default
            #line hidden
, 1350), false)
);

WriteAttribute("person_name", Tuple.Create(" person_name=\"", 1361), Tuple.Create("\"", 1387)
            
            #line 33 "..\..\Views\Person\Partial\_PersonTable.cshtml"
 , Tuple.Create(Tuple.Create("", 1375), Tuple.Create<System.Object, System.Int32>(person.Name
            
            #line default
            #line hidden
, 1375), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">Add</button></td>\r\n            <td>\r\n                <button");

WriteLiteral(" name=\"edit_person\"");

WriteAttribute("edit_id", Tuple.Create(" edit_id=\"", 1489), Tuple.Create("\"", 1509)
            
            #line 35 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1499), Tuple.Create<System.Object, System.Int32>(person.Id
            
            #line default
            #line hidden
, 1499), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">Edit</button>\r\n            </td>\r\n            <td>\r\n                <button");

WriteLiteral(" name=\"delete_person\"");

WriteAttribute("delete_id", Tuple.Create(" delete_id=\"", 1628), Tuple.Create("\"", 1650)
            
            #line 38 "..\..\Views\Person\Partial\_PersonTable.cshtml"
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(person.Id
            
            #line default
            #line hidden
, 1640), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">Delete</button>\r\n            </td>\r\n        </tr>\r\n");

            
            #line 41 "..\..\Views\Person\Partial\_PersonTable.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
