#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCApp;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Person/Partial/_PersonDetails.cshtml")]
    public partial class _Views_Person_Partial__PersonDetails_cshtml : System.Web.Mvc.WebViewPage<MVCApp.ViewModels.PersonViewModel>
    {
        public _Views_Person_Partial__PersonDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"person_table\"");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n        <tr");

WriteLiteral(" class=\"table-header\"");

WriteLiteral(">\r\n            <th>Photo</th>\r\n            <th>Name</th>\r\n            <th>Birthda" +
"te</th>\r\n            <th>Age</th>\r\n            <th>Badges</th>\r\n        </tr>\r\n " +
"           <tr");

WriteAttribute("id", Tuple.Create(" id=\"", 334), Tuple.Create("\"", 348)
            
            #line 12 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
, Tuple.Create(Tuple.Create("", 339), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 339), false)
);

WriteLiteral(">\r\n                <td>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 398), Tuple.Create("\"", 493)
            
            #line 14 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
, Tuple.Create(Tuple.Create("", 404), Tuple.Create<System.Object, System.Int32>(Url.Action("GetPhoto", "Person", new {personId = @Model.Id, fileName = @Model.PhotoUrl})
            
            #line default
            #line hidden
, 404), false)
);

WriteLiteral(" class=\"photoImg\"");

WriteLiteral(" />\r\n                </td>\r\n                <td");

WriteLiteral(" name=\"name\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
                           Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" name=\"birthDate\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
                                Write(Model.BirthDate.ToString("MM/dd/yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 18 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
               Write(Model.Age);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>\r\n                    <div");

WriteLiteral(" class=\"add_badge_container\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
                         foreach (var badge in Model.Badges)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"badge_item\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("img_id", Tuple.Create(" img_id=\"", 965), Tuple.Create("\"", 983)
            
            #line 24 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
, Tuple.Create(Tuple.Create("", 974), Tuple.Create<System.Object, System.Int32>(badge.Id
            
            #line default
            #line hidden
, 974), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 984), Tuple.Create("\"", 1077)
            
            #line 24 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
, Tuple.Create(Tuple.Create("", 990), Tuple.Create<System.Object, System.Int32>(Url.Action("GetImage", "Badge", new {badgeId = @badge.Id, fileName = @badge.ImageUrl})
            
            #line default
            #line hidden
, 990), false)
);

WriteAttribute("title", Tuple.Create(" \r\n                                     title=\"", 1078), Tuple.Create("\"", 1137)
            
            #line 25 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
, Tuple.Create(Tuple.Create("", 1125), Tuple.Create<System.Object, System.Int32>(badge.Title
            
            #line default
            #line hidden
, 1125), false)
);

WriteLiteral(" class=\"photoImg img-circle\"");

WriteLiteral(" />\r\n                            </div>\r\n");

            
            #line 27 "..\..\Views\Person\Partial\_PersonDetails.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </td>\r\n            </tr>\r\n    </table" +
">\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"badgeModal\"");

WriteLiteral(" class=\"modal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"badgeInfo\"");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
